language: go

services: docker

before_install:
  - cd .travis-files/docker
  - docker build --tag splunk .
  - docker run --name splunk splunk
  - docker exec -it splunk /opt/splunk/bin/splunk --accept-license
  - docker ps -a

script:
  - curl -k -admin:changeme https://localhost:8089/services/authentication/current-context
